Repository bpmn-io/bpmnlint, pull requests merged in 2025-02, with the labels that each got.

#164 test: update webpack test fixtures
  test/integration/bundling/test/app.webpack.expected.js
Labels: needs review

#162 chore: improve error message on missing rule hooks
  lib/test-rule.js
  test/spec/linter-spec.mjs
Labels: needs review

#165 Be able to configure meta-data with rules (and pass them to reports)
  lib/linter.js
  lib/types.d.ts
  test/spec/linter-spec.mjs
Labels: needs review

#169 chore: bump eslint-plugin-bpmn-io
  lib/linter.js
  package-lock.json
  package.json
Labels: needs review

#171 Verify resolution of local plug-in + rules
  test/integration/cli-spec.mjs
  test/integration/cli/local-rules/.bpmnlintrc
  test/integration/cli/local-rules/diagram.bpmn
  test/integration/cli/local-rules/lib/bpmnlint-plugin/index.js
  test/integration/cli/local-rules/lib/bpmnlint-plugin/package.json
  test/integration/cli/local-rules/lib/bpmnlint-plugin/rules/no-label-bar.js
  test/integration/cli/local-rules/package.json
Labels: enhancement, needs review

#172 feat: add `correctness` rule set
  config/correctness.js
  test/spec/config-spec.mjs
Labels: needs review

#173 Rework warning on elements that should not be used
  rules/helper.js
  rules/no-complex-gateway.js
  rules/no-inclusive-gateway.js
  test/integration/bundling/test/app.rollup.expected.js
  test/integration/bundling/test/app.webpack.expected.js
  test/rules/no-complex-gateway.mjs
  test/rules/no-inclusive-gateway.mjs
Labels: enhancement, rules, needs review

#174 fix: make `link-event` rule check only BPMN compliance
  CHANGELOG.md
  docs/rules/examples/link-event-correct.png
  docs/rules/examples/link-event-incorrect.bpmn
  docs/rules/examples/link-event-incorrect.png
  docs/rules/link-event.md
  rules/link-event.js
  test/rules/link-event.mjs
  test/rules/link-event/invalid.bpmn
  test/rules/link-event/valid-collaboration.bpmn
  test/rules/link-event/valid.bpmn
Labels: needs review

#176 fix: do not require start and end event in ad-hoc subprocess
  rules/end-event-required.js
  rules/start-event-required.js
  test/integration/bundling/test/app.rollup.expected.js
  test/integration/bundling/test/app.webpack.expected.js
  test/rules/end-event-required.mjs
  test/rules/end-event-required/invalid-sub-process-sub-types.bpmn
  test/rules/end-event-required/valid-sub-process-sub-types.bpmn
  test/rules/start-event-required.mjs
  test/rules/start-event-required/invalid-sub-process-sub-types.bpmn
  test/rules/start-event-required/valid-sub-process-sub-types.bpmn
Labels: needs review

#177 docs: clarify custom plug-in naming and referencing
  README.md
Labels: needs review, documentation
